"""device — 스테레오 분리(합성 프레임), 설정 검증, 브링업 상수 로드, 가짜 VideoCapture 로 Device 전 경로."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from opticmix_vision.device import (
    LAYOUTS, Device, DeviceConfig, DeviceError, StereoFrame, split_stereo,
)


def _pair(h: int = 16, w: int = 24) -> tuple[np.ndarray, np.ndarray]:
    """서로 구분되는 두 반쪽. 왼쪽은 10~, 오른쪽은 200~ 대역."""
    L = (np.arange(h * w, dtype=np.uint8).reshape(h, w) % 50) + 10
    R = (np.arange(h * w, dtype=np.uint8).reshape(h, w) % 50) + 200
    return L, R


# ---------------------------------------------------------------- split_stereo

@pytest.mark.parametrize("layout", LAYOUTS)
def test_split_first_is_left_recovers_halves(layout: str):
    L, R = _pair()
    if layout == "sbs":
        frame = np.hstack([L, R])
    elif layout == "tb":
        frame = np.vstack([L, R])
    else:
        frame = np.stack([L, R], axis=2)
    left, right = split_stereo(frame, layout, "first_is_left")
    assert np.array_equal(left, L) and np.array_equal(right, R)
    assert left.shape == (16, 24)


@pytest.mark.parametrize("layout", LAYOUTS)
def test_split_first_is_right_swaps(layout: str):
    L, R = _pair()
    frame = {"sbs": np.hstack([L, R]), "tb": np.vstack([L, R]), "plane_pack": np.stack([L, R], axis=2)}[layout]
    left, right = split_stereo(frame, layout, "first_is_right")
    assert np.array_equal(left, R) and np.array_equal(right, L)


def test_split_plane_pack_accepts_flat_2d_buffer():
    L, R = _pair()
    flat = np.stack([L, R], axis=2).reshape(16, 48)          # (H, 2W) 인터리브 버퍼
    left, right = split_stereo(flat, "plane_pack", "first_is_left")
    assert np.array_equal(left, L) and np.array_equal(right, R)


def test_split_sbs_bgr_frame_is_converted_to_gray():
    L, R = _pair()
    g = np.hstack([L, R])
    bgr = np.repeat(g[:, :, None], 3, axis=2)                 # mono 를 3채널로 디코드한 경우
    left, right = split_stereo(bgr, "sbs", "first_is_left")
    assert left.ndim == 2 and right.ndim == 2
    assert np.array_equal(left, L) and np.array_equal(right, R)


def test_split_rejects_odd_dimension_and_bad_args():
    with pytest.raises(ValueError, match="sbs"):
        split_stereo(np.zeros((16, 25), np.uint8), "sbs", "first_is_left")
    with pytest.raises(ValueError, match="tb"):
        split_stereo(np.zeros((15, 24), np.uint8), "tb", "first_is_left")
    with pytest.raises(ValueError, match="plane_pack"):
        split_stereo(np.zeros((16, 24, 3), np.uint8), "plane_pack", "first_is_left")
    with pytest.raises(ValueError, match="layout"):
        split_stereo(np.zeros((16, 24), np.uint8), "quad", "first_is_left")
    with pytest.raises(ValueError, match="lr_order"):
        split_stereo(np.zeros((16, 24), np.uint8), "sbs", "left_first")


def test_split_returns_views_when_possible():
    L, R = _pair()
    frame = np.vstack([L, R])
    left, _ = split_stereo(frame, "tb", "first_is_left")
    assert np.shares_memory(left, frame)


# ---------------------------------------------------------------- DeviceConfig

def test_config_requires_layout_and_lr_order():
    with pytest.raises(TypeError):
        DeviceConfig()                                          # type: ignore[call-arg]
    with pytest.raises(ValueError, match="layout"):
        DeviceConfig(layout="side", lr_order="first_is_left")
    with pytest.raises(ValueError, match="lr_order"):
        DeviceConfig(layout="sbs", lr_order="unknown")
    with pytest.raises(ValueError, match="backend"):
        DeviceConfig(layout="sbs", lr_order="first_is_left", backend="gstreamer")
    with pytest.raises(ValueError, match="fourcc"):
        DeviceConfig(layout="sbs", lr_order="first_is_left", fourcc="MJPEG")
    with pytest.raises(ValueError, match="fps"):
        DeviceConfig(layout="sbs", lr_order="first_is_left", fps=0)


_CONSTANTS_PASS = """\
# generated by gt_capture.bringup; paste into gt_capture/sources/oem_uvc.py
# 2026-09-06T00:00:00+00:00 / overall PASS
BACKEND = 'opencv'
DEVICE = 'index 1 (dshow)'
RESOLUTION = (2560, 800)
FPS = 60.0
FOURCC = 'MJPG'
LAYOUT = 'sbs'
LR_ORDER = 'first_is_right'
HALF_SIZE = (1280, 800)
PTS_AVAILABLE = False
PTS_UNIT = 'unknown'
PTS_SOURCE = 'cv2 CAP_PROP_POS_MSEC (driver/host clock, NOT device PTS)'
FRAME_ID_SOURCE = 'counter'
ARRIVAL_JITTER_SIGMA_MS = 0.8123
MANUAL_EXPOSURE_OK = True
MANUAL_GAIN_OK = True
"""


def test_config_from_bringup_constants(tmp_path: Path):
    p = tmp_path / "oem_uvc_constants.py"
    p.write_text(_CONSTANTS_PASS, encoding="utf-8")
    cfg = DeviceConfig.from_bringup_constants(p)
    assert cfg.device == 1 and cfg.backend == "dshow"
    assert (cfg.width, cfg.height, cfg.fps, cfg.fourcc) == (2560, 800, 60.0, "MJPG")
    assert cfg.layout == "sbs" and cfg.lr_order == "first_is_right"
    over = DeviceConfig.from_bringup_constants(p, device=0, to_gray=False)
    assert over.device == 0 and over.to_gray is False


@pytest.mark.parametrize("patch, msg", [
    ("BACKEND = 'ffmpeg'", "OpenCV"),
    ("LAYOUT = 'single'", "LAYOUT"),
    ("LR_ORDER = 'undetermined'", "LR_ORDER"),
])
def test_config_from_constants_refuses_to_guess(tmp_path: Path, patch: str, msg: str):
    key = patch.split(" =")[0]
    text = "\n".join(patch if line.startswith(key + " =") else line for line in _CONSTANTS_PASS.splitlines())
    p = tmp_path / "c.py"
    p.write_text(text, encoding="utf-8")
    with pytest.raises(ValueError, match=msg):
        DeviceConfig.from_bringup_constants(p)


# ---------------------------------------------------------------- Device (가짜 VideoCapture)

class FakeCapture:
    """cv2.VideoCapture 의 get/set/read/isOpened/release 만 흉내 낸다."""

    def __init__(self, frames: list[np.ndarray], *, opened: bool = True) -> None:
        import cv2
        self._frames = list(frames)
        self._opened = opened
        self.props: dict[int, float] = {cv2.CAP_PROP_FRAME_WIDTH: 0, cv2.CAP_PROP_FRAME_HEIGHT: 0,
                                        cv2.CAP_PROP_FPS: 0, cv2.CAP_PROP_FOURCC: 0}
        self.set_calls: list[tuple[int, float]] = []
        self.released = False

    def isOpened(self) -> bool:
        return self._opened

    def get(self, pid: int) -> float:
        return float(self.props.get(pid, 0.0))

    def set(self, pid: int, value: float) -> bool:
        self.set_calls.append((pid, value))
        self.props[pid] = value                              # 요청 그대로 협상됐다고 가정
        return True

    def read(self):
        if not self._frames:
            return False, None
        return True, self._frames.pop(0)

    def release(self) -> None:
        self.released = True

    def getBackendName(self) -> str:
        return "FAKE"


def test_device_reads_stereo_frames_and_reports_negotiated_mode():
    import cv2
    L, R = _pair()
    frames = [np.hstack([L, R]), np.hstack([L, R])]
    cap = FakeCapture(frames)
    cfg = DeviceConfig(layout="sbs", lr_order="first_is_left", width=48, height=16, fps=30.0, fourcc="MJPG",
                       extra_props={"CAP_PROP_AUTO_EXPOSURE": 0.25})
    with Device(cfg, capture=cap) as cam:
        assert cam.is_open
        assert cam.mode.width == 48 and cam.mode.height == 16 and cam.mode.fps == 30.0
        assert cam.mode.fourcc == "MJPG" and cam.mode.backend_name == "FAKE"
        assert (cv2.CAP_PROP_AUTO_EXPOSURE, 0.25) in cap.set_calls
        f0 = cam.read()
        f1 = cam.read()
        assert isinstance(f0, StereoFrame)
        assert np.array_equal(f0.left, L) and np.array_equal(f0.right, R)
        assert f0.size == (24, 16)
        assert (f0.index, f1.index) == (0, 1)
        assert f1.host_ns >= f0.host_ns > 0
        with pytest.raises(DeviceError, match="읽기 실패"):
            cam.read()                                       # 프레임 소진 → 조용한 실패 금지
    assert cap.released is False                             # 주입한 capture 는 SDK 가 닫지 않는다
    assert cam.is_open is False


def test_device_plane_pack_disables_rgb_conversion():
    import cv2
    L, R = _pair()
    cap = FakeCapture([np.stack([L, R], axis=2)])
    with Device(DeviceConfig(layout="plane_pack", lr_order="first_is_left"), capture=cap) as cam:
        assert (cv2.CAP_PROP_CONVERT_RGB, 0.0) in cap.set_calls
        f = cam.read()
        assert np.array_equal(f.left, L) and np.array_equal(f.right, R)


def test_device_open_failure_raises():
    cap = FakeCapture([], opened=False)
    with pytest.raises(DeviceError, match="열기 실패"):
        Device(DeviceConfig(layout="sbs", lr_order="first_is_left"), capture=cap).open()


def test_device_prop_passthrough_by_name_and_id():
    import cv2
    cap = FakeCapture([])
    cam = Device(DeviceConfig(layout="sbs", lr_order="first_is_left"), capture=cap).open()
    assert cam.set_prop("CAP_PROP_GAIN", 7) is True
    assert cam.get_prop(cv2.CAP_PROP_GAIN) == 7.0
    with pytest.raises(DeviceError):
        Device(DeviceConfig(layout="sbs", lr_order="first_is_left")).get_prop("CAP_PROP_GAIN")
