"""캘리브 JSON → ROS `camera_info` YAML. 의존성 없음(문자열로 직접 쓴다).

ROS 는 Kannala-Brandt 4차를 **`equidistant`** 라고 부른다(OpenCV `cv2.fisheye` 와 같은 모델).
`image_pipeline` / `camera_calibration_parsers` 가 읽는 키 이름과 행렬 모양이 정확해야 하므로
그 구조를 그대로 만든다:

    image_width / image_height / camera_name
    camera_matrix            3×3  (K, 원본 픽셀)
    distortion_model         equidistant
    distortion_coefficients  1×4  (k1..k4)
    rectification_matrix     3×3  (R1 또는 R2 — 정류 회전)
    projection_matrix        3×4  (P1 / P2, **미터 단위 베이스라인**)

단위 함정: 우리 캘리브 JSON 의 t 는 **mm**, ROS 의 P[0,3] = −fx·B 는 **m** 다. 여기서 나눈다.
부호도 ROS 규약(오른쪽 카메라가 음수)을 따른다.

사용:
    python -m opticmix_vision.calibrate ... --ros-camera-info-dir ros_calib/
    # 또는
    from opticmix_vision.ros import write_stereo_camera_info
    write_stereo_camera_info(calib, "ros_calib", maps=maps, name_prefix="omv_s1")

usb_cam(ROS 2) 연결은 `docs/ros2_usb_cam.md` 참조.
"""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

import numpy as np

from .calibration import CameraIntrinsics, StereoCalibration
from .rectify import RectifyMaps

__all__ = ["camera_info_yaml", "write_stereo_camera_info"]

_EYES = ("left", "right")


def _rows(name: str, m: np.ndarray) -> str:
    a = np.asarray(m, dtype=np.float64)
    data = ", ".join(f"{v:.10g}" for v in a.reshape(-1))
    return (f"{name}:\n"
            f"  rows: {a.shape[0]}\n"
            f"  cols: {a.shape[1]}\n"
            f"  data: [{data}]\n")


def camera_info_yaml(intr: CameraIntrinsics, *, frame_id: str, maps: RectifyMaps | None = None,
                     eye: str | None = None) -> str:
    """한 눈의 camera_info YAML 문자열.

    `maps` 를 주면 정류 회전(R1/R2)과 투영행렬(P1/P2)을 그대로 싣는다 — 스테레오로 쓰려면 필수다.
    주지 않으면 R = 단위행렬, P = [K | 0] 으로 두고 **미정류임을 주석으로 남긴다**.
    """
    if maps is not None:
        if eye not in _EYES:
            raise ValueError(f"maps 를 주면 eye 는 'left' 또는 'right' 여야 한다: {eye!r}")
        R = maps.R1 if eye == "left" else maps.R2
        P = np.array(maps.P1 if eye == "left" else maps.P2, dtype=np.float64).copy()
        P[0, 3] = P[0, 3] / 1000.0                 # mm → m (ROS 규약: P2[0,3] = -fx·B[m])
        note = (f"# 정류 파라미터 포함 (eye={eye}). P[0,3] 은 ROS 규약대로 미터 단위다.\n"
                f"# rectified_focal_px={maps.rectified_focal_px:.6g}, "
                f"baseline_mm={maps.baseline_from_P2_mm:.6g}\n")
        w, h = maps.size
    else:
        R = np.eye(3)
        P = np.hstack([np.asarray(intr.K, dtype=np.float64), np.zeros((3, 1))])
        note = ("# WARNING: rectification not included — R=I, P=[K|0].\n"
                "# 정류 파라미터 없이 스테레오로 쓰면 시차·깊이가 틀린다. maps 를 넘겨 다시 생성할 것.\n")
        w, h = intr.size

    head = ("# generated by opticmix_vision.ros — do not edit by hand\n"
            "# model: Kannala-Brandt 4 (OpenCV cv2.fisheye) == ROS distortion_model 'equidistant'\n"
            + note)
    body = (f"image_width: {int(w)}\n"
            f"image_height: {int(h)}\n"
            f'camera_name: "{frame_id}"\n'
            + _rows("camera_matrix", np.asarray(intr.K, dtype=np.float64))
            + "distortion_model: equidistant\n"
            + _rows("distortion_coefficients", np.asarray(intr.D, dtype=np.float64).reshape(1, 4))
            + _rows("rectification_matrix", np.asarray(R, dtype=np.float64))
            + _rows("projection_matrix", P))
    return head + body


def write_stereo_camera_info(calib: StereoCalibration, out_dir: str | Path, *,
                             maps: RectifyMaps | None = None, name_prefix: str = "camera"
                             ) -> list[Path]:
    """좌·우 camera_info YAML 두 개를 쓰고 경로를 (left, right) 순으로 반환."""
    d = Path(out_dir)
    d.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    for eye, intr in (("left", calib.left), ("right", calib.right)):
        name = f"{name_prefix}_{eye}"
        text = camera_info_yaml(intr, frame_id=name, maps=maps, eye=eye if maps is not None else None)
        p = d / f"{name}.yaml"
        p.write_text(text, encoding="utf-8")
        paths.append(p)
    return paths
